### PR TITLE
A README.rst fix + Python 2 compatibility

### PR DESCRIPTION
**Pull request by estan**
Tested with Python 2.7.9.

### CODE REVIEW

**Comment by estan** [comment]
Would love a new release on PyPI if you pull these in. It's advertised as Python 2 compatible there after all :)

**Comment by ColinDuquesnoy** [comment]
Thanks! I'll make a new release on pypi soon!

**Comment by ColinDuquesnoy** [comment]
@estan The new version (0.4.2) is available on pypi

**Comment by estan** [comment]
:thumbsup:

**Pull request merged**
